//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspecialistaTrabajador
    {
        public int EspecialistaTrabajadorId { get; set; }
        public string AreaTrabajo { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public int Trabajador_TrabajadorId { get; set; }
        public int Especialista_EspecialistaId { get; set; }
        public int UsuarioCreacionId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioModificacionId { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual Especialista Especialista { get; set; }
        public virtual Trabajador Trabajador { get; set; }
    }
}
