//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Especialista()
        {
            this.EspecialistaTrabajador = new HashSet<EspecialistaTrabajador>();
        }
    
        public int EspecialistaId { get; set; }
        public string DniEspecialista { get; set; }
        public string Contrasena { get; set; }
        public string NombreEspecialista { get; set; }
        public string ApellidoEspecialista { get; set; }
        public string Ocupacion { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public int UsuarioCreacionId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioModificacionId { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EspecialistaTrabajador> EspecialistaTrabajador { get; set; }
    }
}
