//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Trabajo_Final : DbContext
    {
        public Trabajo_Final()
            : base("name=Trabajo_Final")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Especialista> Especialista { get; set; }
        public virtual DbSet<EspecialistaTrabajador> EspecialistaTrabajador { get; set; }
        public virtual DbSet<RegistroConsumoMetabolico> RegistroConsumoMetabolico { get; set; }
        public virtual DbSet<RegistroMonitoreoErgonomico> RegistroMonitoreoErgonomico { get; set; }
        public virtual DbSet<RegistroResistenciaTermica> RegistroResistenciaTermica { get; set; }
        public virtual DbSet<RegistroTrabajador> RegistroTrabajador { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
    }
}
